# Generated by Django 5.2.3 on 2025-06-22 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('short_title', models.CharField(blank=True, max_length=50)),
                ('authors', models.CharField(blank=True, max_length=200)),
                ('publish_date', models.CharField(blank=True, max_length=50)),
                ('summary', models.TextField()),
                ('top_image', models.URLField(blank=True, null=True)),
                ('sentiment', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
